//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeedrunTracker.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpeedrunTracker.Resources.Localization.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by Stefan Frijters in .NET MAUI with data provided by the speedrun.com REST API..
        /// </summary>
        internal static string AboutPageCreditsLabel {
            get {
                return ResourceManager.GetString("AboutPageCreditsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Tracker.
        /// </summary>
        internal static string AboutPageIssueTrackerButton {
            get {
                return ResourceManager.GetString("AboutPageIssueTrackerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please report any issues you may encounter on the issue tracker..
        /// </summary>
        internal static string AboutPageIssueTrackerLabel {
            get {
                return ResourceManager.GetString("AboutPageIssueTrackerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string AboutPagePrivacyPolicyButton {
            get {
                return ResourceManager.GetString("AboutPagePrivacyPolicyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions.
        /// </summary>
        internal static string AboutPageTermsAndConditionsButton {
            get {
                return ResourceManager.GetString("AboutPageTermsAndConditionsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpeedrunTracker.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be logged in to view this content..
        /// </summary>
        internal static string BaseNetworkActionForbiddenToast {
            get {
                return ResourceManager.GetString("BaseNetworkActionForbiddenToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet access..
        /// </summary>
        internal static string BaseNetworkActionNoInternetAccessToast {
            get {
                return ResourceManager.GetString("BaseNetworkActionNoInternetAccessToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received an unknown error from the speedrun.com API..
        /// </summary>
        internal static string BaseNetworkActionUnknownErrorToast {
            get {
                return ResourceManager.GetString("BaseNetworkActionUnknownErrorToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string DialogNoButton {
            get {
                return ResourceManager.GetString("DialogNoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string DialogOkButton {
            get {
                return ResourceManager.GetString("DialogOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string DialogYesButton {
            get {
                return ResourceManager.GetString("DialogYesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string EntitySubtitleCreated {
            get {
                return ResourceManager.GetString("EntitySubtitleCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered.
        /// </summary>
        internal static string EntitySubtitleRegistered {
            get {
                return ResourceManager.GetString("EntitySubtitleRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released.
        /// </summary>
        internal static string EntitySubtitleReleased {
            get {
                return ResourceManager.GetString("EntitySubtitleReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string EntitySubtitleUnknown {
            get {
                return ResourceManager.GetString("EntitySubtitleUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added &quot;{0}&quot; to your favorites..
        /// </summary>
        internal static string FavoritesPageAddedToFavoritesToast {
            get {
                return ResourceManager.GetString("FavoritesPageAddedToFavoritesToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        internal static string FavoritesPageFavoriteButton {
            get {
                return ResourceManager.GetString("FavoritesPageFavoriteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks like you have not yet added any games, series or users to your favorites!
        ///
        ///Search for a game, series or user and hit the Favorite button to add them to this list..
        /// </summary>
        internal static string FavoritesPagePlaceholderLabel {
            get {
                return ResourceManager.GetString("FavoritesPagePlaceholderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed &quot;{0}&quot; from your favorites..
        /// </summary>
        internal static string FavoritesPageRemovedFromFavoritesToast {
            get {
                return ResourceManager.GetString("FavoritesPageRemovedFromFavoritesToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfavorite.
        /// </summary>
        internal static string FavoritesPageUnfavoriteButton {
            get {
                return ResourceManager.GetString("FavoritesPageUnfavoriteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Game.
        /// </summary>
        internal static string GameDetailPageFullGameButton {
            get {
                return ResourceManager.GetString("GameDetailPageFullGameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for games....
        /// </summary>
        internal static string GameSearchPagePlaceholderText {
            get {
                return ResourceManager.GetString("GameSearchPagePlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for game series....
        /// </summary>
        internal static string GameSeriesSearchPagePlaceholderText {
            get {
                return ResourceManager.GetString("GameSeriesSearchPagePlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MenuItemAboutTitle {
            get {
                return ResourceManager.GetString("MenuItemAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string MenuItemFavoritesTitle {
            get {
                return ResourceManager.GetString("MenuItemFavoritesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string MenuItemNotificationsTitle {
            get {
                return ResourceManager.GetString("MenuItemNotificationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string MenuItemProfileTitle {
            get {
                return ResourceManager.GetString("MenuItemProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series.
        /// </summary>
        internal static string MenuItemSearchGameSeriesTabTitle {
            get {
                return ResourceManager.GetString("MenuItemSearchGameSeriesTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        internal static string MenuItemSearchGamesTabTitle {
            get {
                return ResourceManager.GetString("MenuItemSearchGamesTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string MenuItemSearchTitle {
            get {
                return ResourceManager.GetString("MenuItemSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string MenuItemSearchUsersTabTitle {
            get {
                return ResourceManager.GetString("MenuItemSearchUsersTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MenuItemSettingsTitle {
            get {
                return ResourceManager.GetString("MenuItemSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided API key is invalid..
        /// </summary>
        internal static string ProfilePageApiKeyErrorToast {
            get {
                return ResourceManager.GetString("ProfilePageApiKeyErrorToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        internal static string ProfilePageGuestLabel {
            get {
                return ResourceManager.GetString("ProfilePageGuestLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to log out?.
        /// </summary>
        internal static string ProfilePageLogoutMessage {
            get {
                return ResourceManager.GetString("ProfilePageLogoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string ProfilePageLogoutTitle {
            get {
                return ResourceManager.GetString("ProfilePageLogoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No API key provided..
        /// </summary>
        internal static string ProfilePageNoApiKeyErrorToast {
            get {
                return ResourceManager.GetString("ProfilePageNoApiKeyErrorToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting profile data.
        /// </summary>
        internal static string ProfilePageUnknownErrorToast {
            get {
                return ResourceManager.GetString("ProfilePageUnknownErrorToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        internal static string RunDetailsPageStatusRejectedText {
            get {
                return ResourceManager.GetString("RunDetailsPageStatusRejectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification pending.
        /// </summary>
        internal static string RunDetailsPageStatusVerificationPendingText {
            get {
                return ResourceManager.GetString("RunDetailsPageStatusVerificationPendingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified on {0} at {1}.
        /// </summary>
        internal static string RunDetailsPageStatusVerifiedOnText {
            get {
                return ResourceManager.GetString("RunDetailsPageStatusVerifiedOnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified.
        /// </summary>
        internal static string RunDetailsPageStatusVerifiedText {
            get {
                return ResourceManager.GetString("RunDetailsPageStatusVerifiedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        internal static string RunDetailsPageSubtitleByText {
            get {
                return ResourceManager.GetString("RunDetailsPageSubtitleByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by &lt;unknown&gt;.
        /// </summary>
        internal static string RunDetailsPageSubtitleByUnknownText {
            get {
                return ResourceManager.GetString("RunDetailsPageSubtitleByUnknownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string RunDetailsPageSubtitlePlayerSeparator {
            get {
                return ResourceManager.GetString("RunDetailsPageSubtitlePlayerSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        internal static string RunDetailsPageTitleInText {
            get {
                return ResourceManager.GetString("RunDetailsPageTitleInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Format.
        /// </summary>
        internal static string SettingePageTimeFormatItem {
            get {
                return ResourceManager.GetString("SettingePageTimeFormatItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Backgrounds.
        /// </summary>
        internal static string SettingsPageBackgroundsItem {
            get {
                return ResourceManager.GetString("SettingsPageBackgroundsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string SettingsPageDarkTheme {
            get {
                return ResourceManager.GetString("SettingsPageDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Format.
        /// </summary>
        internal static string SettingsPageDateFormatItem {
            get {
                return ResourceManager.GetString("SettingsPageDateFormatItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and Time.
        /// </summary>
        internal static string SettingsPageDateTimeGroupHeader {
            get {
                return ResourceManager.GetString("SettingsPageDateTimeGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface.
        /// </summary>
        internal static string SettingsPageInterfaceGroupHeader {
            get {
                return ResourceManager.GetString("SettingsPageInterfaceGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string SettingsPageLightTheme {
            get {
                return ResourceManager.GetString("SettingsPageLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Leaderboard Results.
        /// </summary>
        internal static string SettingsPageMaximumLeaderboardResultsGroupHeader {
            get {
                return ResourceManager.GetString("SettingsPageMaximumLeaderboardResultsGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Default.
        /// </summary>
        internal static string SettingsPageSystemTheme {
            get {
                return ResourceManager.GetString("SettingsPageSystemTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string SettingsPageThemeItem {
            get {
                return ResourceManager.GetString("SettingsPageThemeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string SpinnerLoadingText {
            get {
                return ResourceManager.GetString("SpinnerLoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        internal static string SpinnerSearchingText {
            get {
                return ResourceManager.GetString("SpinnerSearchingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for users....
        /// </summary>
        internal static string UserSearchPagePlaceholderText {
            get {
                return ResourceManager.GetString("UserSearchPagePlaceholderText", resourceCulture);
            }
        }
    }
}
